version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        DOCKER_ROOT: ${DOCKER_ROOT}
        DJANGO_ROOT: ${DJANGO_ROOT}
    image: django-app
    restart: always
    volumes:
      - ${DJANGO_ROOT}:/code
    env_file:
      - .env
    ports:
      - "8000:8000"
#  celery:
#    image: django-app
#    restart: always
#    command: ["runcelery.sh"]
#    volumes:
#      - ${DJANGO_ROOT}:/code
#    env_file:
#      - .env
#    depends_on:
#      - app
#      - rabbitmq

  nginx:
    image: nginx:alpine
    restart: always
    volumes:
      - ${DJANGO_ROOT}/media/:/var/www/media/
      - ${DJANGO_ROOT}/assets/:/var/www/assets/:ro
      - ${DOCKER_ROOT}/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - app
#   RabbitMQ - queue
#   rabbitmq:
#       image: rabbitmq:3-management
#       # restart: always
#       environment:
#           - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
#           - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
#       # ports:
#       #     - "5672:5672"
#       #     - "15672:15672"
#  db:
#    image: postgres:alpine
#    environment:
#      POSTGRES_DB: ${DATABASE_NAME}
#      POSTGRES_USER: ${DATABASE_USER}
#      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}

